# Generated by Django 3.2.5 on 2022-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.CharField(max_length=2000)),
                ('time', models.TimeField()),
                ('ingredients', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('serving_size', models.IntegerField()),
            ],
        ),
    ]
