# Generated by Django 3.2.5 on 2022-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='serving_size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='time',
            field=models.DurationField(),
        ),
    ]
