# Generated by Django 3.2.5 on 2022-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220129_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='image',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
