# Generated by Django 3.2.5 on 2022-01-29 17:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_recipemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=django_mysql.models.ListTextField(models.CharField(max_length=125), size=20),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='recipe',
            field=django_mysql.models.ListTextField(models.CharField(max_length=1000), size=15),
        ),
    ]
